version: '3.1'

services:
  Myspring:
    image: praveenadmin/spring-boot-mongo:1
    ports:
      - 8080:8080
    networks:
    - mynetwork  
  mongo:
    image: mongo
    volumes:
      - mongodb:/data/db
    restart: always
    networks:
    - mynetwork
    
volumes:
  mongodb:
    external: true
    
networks:
  mynetwork:
    external: true