version: '3.1'
services:
  Myspring:
   environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=QAdb
    - MONGO_DB_PASSWORD=QAdb@123
   mongo:
   environment:
    - MONGO_INITDB_ROOT_USERNAME=QAdb
    - MONGO_INITDB_ROOT_PASSWORD=QAdb@123   